name: Publish to Nuget
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.0.100
      - name: Build
        run: dotnet build --configuration Release
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push
        run: dotnet nuget push **/*.nupkg
              --api-key ${{ secrets.NUGET_API_KEY }}
              --source https://api.nuget.org/v3/index.json
              --no-symbols true  
